@startuml

title __SERVER's Class Diagram__\n

  namespace Server {
    class Server.CommunicationServer {
        - datagramSocket : DatagramSocket
        + CommunicationServer()
        + listen()
        - AnswerToClient()
    }
  }
  

  namespace Server {
    class Server.CsvReader {
        + read()
        {static} - getEye()
        {static} - getMpaaRating()
    }
  }
  

  namespace Server {
    class Server.KeyboardHandler {
        + run()
    }
  }
  

  namespace Server {
    class Server.ProcessHandler {
        ~ compareByOscars : Comparator<Movie>
        + processCommand()
        + save()
        - clear()
        - countLessThanOscarsCount()
        - executeCommand()
        - executeScript()
        - getLine()
        {static} - getNewId()
        - help()
        - info()
        - insert()
        - printAscending()
        - printFieldDescendingOscarsCount()
        - remove()
        - remove_greater_key()
        - replaceIfGreater()
        - replaceIfLower()
        - show()
        - update()
    }
  }
  

  namespace Server {
    class Server.ServerApp {
        {static} + movieHashtable : Hashtable<Long, Movie>
        {static} - exit : Boolean
        {static} - fileName : String
        {static} - initialization : String
        {static} + getExit()
        {static} + getFileName()
        {static} + getInitialization()
        {static} + main()
        {static} + setExit()
        {static} + setInitialization()
        {static} - createIfNotExists()
        {static} - setFileName()
    }
  }
  

  Server.KeyboardHandler .up.|> java.lang.Runnable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
